# GitHub Actions Workflow: Production Deployment with Migrations
#
# This workflow runs database migrations and deploys to production
# when changes are merged to main.
#
# Required secrets:
# - DATABASE_URL_UNPOOLED: Direct connection string for migrations
# - VERCEL_TOKEN: Your Vercel token
# - VERCEL_ORG_ID: Your Vercel org ID
# - VERCEL_PROJECT_ID: Your Vercel project ID

name: Production Deployment

on:
  push:
    branches: [main]

concurrency:
  group: production
  cancel-in-progress: false  # Don't cancel production deploys

jobs:
  # ==========================================================================
  # RUN MIGRATIONS
  # ==========================================================================
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run database migrations
        env:
          # IMPORTANT: Use unpooled (direct) connection for migrations
          DATABASE_URL: ${{ secrets.DATABASE_URL_UNPOOLED }}
        run: npx drizzle-kit migrate
        # Or for Prisma: npx prisma migrate deploy
        
      - name: Verify migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_UNPOOLED }}
        run: |
          # Optional: Run a quick validation query
          echo "Migration completed successfully"

  # ==========================================================================
  # DEPLOY TO PRODUCTION
  # ==========================================================================
  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy to Production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  # ==========================================================================
  # NOTIFY (Optional)
  # ==========================================================================
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify on success
        if: needs.deploy.result == 'success'
        run: |
          echo "✅ Production deployment successful"
          # Add Slack/Discord notification here
          
      - name: Notify on failure
        if: needs.deploy.result == 'failure'
        run: |
          echo "❌ Production deployment failed"
          # Add Slack/Discord notification here
